### ISSUE TITLE
need glossary

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#12]
From Jim Larson's email [https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0004.html](url)

The relationship among the following entities is not clear:

·Session (3.3.2)

·Dialog management (3.2.2)

·Dialog (3.2.8

·Core dialog (3.2.8.1)

·Dialog x (3.2.8.5

·Intent set (3.2.8.4)

May I suggest a small glossary of terms that defines these entities and 
their relationships. The glossary should also include “voice registry” 
which is a Open Voice Network term for a registry for “voice 
applications”.A “voice application” may contain several dialogs.

**Comment by dadahl** [comment]
We agree that we need a glossary, but may not be able to assign to anyone

**Comment by dadahl** [comment]
Jim: let's postpone the glossary for this publication

**Comment by schnelle** [comment]
Maybe not needed as all terms are explained in the document. Having a glossary would result in having to synchronize the definitions with the description in the text.
