### ISSUE TITLE
relationship to OVN Voice Registry

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#13]
from Jim Larson's email [https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0004.html](url)

3.2.8.7The OVN’s Voice Registry System contains dialogs that a 
registered with OVN and are available for use by all IPAs.A subset of 
them may be downloaded to IPA’s local dialog registry. (It is important 
to note the OVN Voice Registry System is a world wide resource similar 
to DNA and should not be confused with the similarly named IPA voice 
registry

**Comment by schnelle** [comment]
Will have to be delayed until the OVN Voice Registry is publicly available.

**Comment by schnelle** [comment]
Decision not to wait for OVON to publish and close the issue.
