### ISSUE TITLE
provider NLU

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#15]
From Jim Larson's email [https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0004.html](url)

3.3.4.2 Provider NLU

There is a NLU in the orange Dialog box and several Provider NLUs in the 
blue API/Data box.There appear to be two systems (1) the orange 
GENERAL-PURPOSE system which handles simple, common requests, and (2) 
several blue SPECIFIC PURSE systems for handling specific domains.Is 
this correct?

**Comment by dadahl** [comment]
Let's clarify this distinction in the text
jim: we should have two terms , one for each kind of NLU, and define in text

**Comment by schnelle** [comment]
The NLU in the dialog layer (orange box) is referred to as "NLU"
The NLU in the External Data / Services / IPA Providers - Layer is referred to as "Provider NLU"

Both are not related to any specific purpose, be it general or specific. However, the Provider NLU may be specific but could also be a general purpose NLU. I added some more details for the Provider NLU to make this clearer
