### ISSUE TITLE
relate Provider selection service and Voice Registry

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#19]
•	Regarding the Provider Selection Service, which I perceived to be the primary “secret sauce” within this work:
o	I would very much (Jim, your thoughts, please) connect this thinking to the Voice Registry concepts now percolating within the Open Voice Network.
o	Of most interest to me was the IPA to IPA connection; am I correct that we identify here a “what” but have yet to determine the “how?”

**Comment by schnelle** [comment]
Voice Registry is a term from OVON which is a non-related activity. Also, I am not aware of any public documents that could be referenced. I suggest to close this issue without any further action.
