### ISSUE TITLE
problem statement

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#3]
from Jim Larson's email: https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0002.html
I find this confusing.Is it hardware transparency, interoperability, or 
extensibility?

Include principles used to decide how partition the architecture into 
boxes, such as separation of concerns, each box does a single activity, 
etc.

**Comment by dadahl** [comment]
discussion from March 10 call [https://www.w3.org/2021/03/10-voiceinteraction-minutes.html](url)

jim: what is the problem?

debbie: I think it's interoperability

jim: I think that's the main purpose
… describe principles about how the partition was arrived at
… general software principles could be referenced
… there is a nice hierarchical partitioning

debbie: we were using a traditional partitioning for conversational systems

jim: this should be included in the document
debbie: agree

**Comment by schnelle** [comment]
@schnelle to add SW principle
@dadahl to add problem statement

**Comment by schnelle** [comment]
added SOLID principle to section 3. architecture

**Comment by schnelle** [comment]
@schnelle to better match the SOLID principle explanation to the document

**Comment by schnelle** [comment]
Detailed the solid principle for this document

**Comment by schnelle** [comment]
Open point: @dadahl to add problem statement

**Comment by schnelle** [comment]
@dadahl I think that this issue is addressed by adding the SOLID principle. I suggest to close it if non objects.
