### ISSUE TITLE
Add roles and responsibilities

### ISSUE THREAD

**Issue by schnelle** [w3c/voiceinteraction#36]
Section "2.2 Roles and Responsibilities" of the architecture document is a place holder and need to receive some content

**Comment by schnelle** [comment]
Roles and Responsibilities, using the RACI model (responsible, accountable, consulted, informed)

Platform provider (example: Google)
- accountable and responsible for the operative performance of the infrastructure (uptime, security, performance as measured against service-level agreements (SLAs) with clients, customers, and partners, inclusive of on-premises hardware and cloud services. 

Content owner (example:  a financial services enterprise, such as a bank)
- Accountable for the UX, content, and operational performance of any and all assistants that represent the brand and its services to brand constituents (including clients, customers, and internal stakeholders).

Developer (Most often, an independent enterprise specializing in conversational assistance; example: RASA)  Responsible to the content owner for the
-  selection of the hosting and infrastructure services
- definition and development of the IPA
- design and definition of IPA possibilities and basic functionalities: activation strategies, architecture tailoring, hardware specifications
- may define and develop conversational content 

Designer and Application Developer (example:  Vixen Labs, London)  Responsible to the content owner for
- definition, design of the conversational interaction on behalf of a brand or client organization (Developer is consulted)
- definition, development, editing of content on behalf of a brand or client organization
- creating applications extending the basic functionalities

System Integrator  (examples:  Capgemini Consulting, Deloitte) -- responsible to content owner for
- Business process analysis:  where, how conversational assistance will create value
- Definition, development of business process transformation flow and interfaces -- where/how/through what knowledge is transmitted to action
- Creation and integration of access for conversational assistant into necessary corporate data sources
- Development of  system/process ROI and NPV analyses of investment
 
User
- uses the IPA

**Comment by jcstine** [comment]
Proposed revisions, J. Stine, 2023.10.23

**Comment by nwhysel** [comment]
I don’t see an attachment. Was it scrubbed by the list?NoreenOn Oct 23, 2023, at 5:16 PM, Jon Stine ***@***.***> wrote:﻿
Proposed revisions, J. Stine, 2023.10.23

**Comment by nwhysel** [comment]
Oh nm. Just realized it was a GitHub issue.NoreenOn Oct 23, 2023, at 8:59 PM, Noreen Whysel ***@***.***> wrote:﻿I don’t see an attachment. Was it scrubbed by the list?NoreenOn Oct 23, 2023, at 5:16 PM, Jon Stine ***@***.***> wrote:﻿
Proposed revisions, J. Stine, 2023.10.23

**Comment by schnelle** [comment]
@jcstine  could you re-share your proposed revision here as a comment?

**Comment by jcstine** [comment]
Per Dirk's request of 2023.12.13 --

Draft suggestion for roles and responsibilities

Owner/Platform provider

in charge of the physical hardware
Designer

Roles and Responsibilities, using the RACI model (responsible, accountable, consulted, informed)

Platform provider (example: Google)

accountable and responsible for the operative performance of the infrastructure (uptime, security, performance as measured against service-level agreements (SLAs) with clients, customers, and partners, inclusive of on-premises hardware and cloud services.
Content owner (example: a financial services enterprise, such as a bank)

Accountable for the UX, content, and operational performance of any and all assistants that represent the brand and its services to brand constituents (including clients, customers, and internal stakeholders).
Developer (Most often, an independent enterprise specializing in conversational assistance; example: RASA) Responsible to the content owner for the

responsible for the development of the IPA
selection of the hosting and infrastructure services
definition and development of the IPA
designs and definesdefinition of IPA possibilities and basic functionalities: activation strategies, architecture tailoring, hardware specifications, ...
may define and develop conversational content
Application developer

Designer and Application Developer (example: Vixen Labs, London) Responsible to the content owner for

definition, design of the conversational interaction on behalf of a brand or client organization (Developer is consulted)
definition, development, editing of content on behalf of a brand or client organization
createscreating applications extending the basic functionialities
Integrator

manufacturer of services
maintainer of data providers
System Integrator (examples: Capgemini Consulting, Deloitte) -- responsible to content owner for

Business process analysis: where, how conversational assistance will create value
Definition, development of business process transformation flow and interfaces -- where/how/through what knowledge is transmitted to action
Creation and integration of access for conversational assistant into necessary corporate data sources
Development of system/process ROI and NPV analyses of investment
User

uses the IPA

**Comment by jcstine** [comment]
Dirk, thanks for the note, and apologies for process mistakes on my side.

 

Have entered the proposed revision as a comment as requested.

 

Jon

 

Jon Stine

 ***@***.***> ***@***.***

+1 503 449 4628

**Comment by schnelle** [comment]
@dadahl please review the suggested addition by @jcstine and add it to the document

**Comment by schnelle** [comment]
Content wise OK, but examples to be removed.

**Comment by schnelle** [comment]
Review in meeting on 2024-06-05
OK to close
