### ISSUE TITLE
Placement of capturing and presentation components

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#5]
from Jim Larson's email [https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0002.html](url)

3.Architecture

Begin this section with three boxes labeled client, dialog, and 
APIs/Data. Then have 3 additional pictures, one for each box enlarged to 
show its contents.

Replace “microphone” by “capture” and then have a separate box to 
indicate alternative capturae techniques, including <microphone, ASR> < 
camera, vision algorithm>, <sensor, sensor interpreter> <joystick, 
joystsick interpreter> etc.

Replace “speaker” by “presentation” and then have a separate box to 
indicate alternative presentation techniques including <speaker, tts>, 
<screen, layout renderer> and <actuator, actuator activator>

Move TTS and ASR out of the dialog into the client box.They are user 
interface techniques rather than dialog techniques

**Comment by schnelle** [comment]
The current diagrams reflect the approach that we find in current deployments. Further in-depth discussion is needed how to separate a logical view as described in the issue vs. current deployments.

**Comment by schnelle** [comment]
Please, review @dadahl, @jcstine

**Comment by schnelle** [comment]
Images should be changed (text is correct)

- keyboard is a capture device and not a presentation device
- screen is a presentation device and not a capture device

**Comment by dadahl** [comment]
These changes look good.

**Comment by schnelle** [comment]
Agreed in the sync call to close the issue.
