### ISSUE TITLE
define session

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#6]
from Jim Larson's email https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0002.html

3.3.2 dialog management(second to last bullet)

Undefined term: session

**Comment by schnelle** [comment]
introduced section 3.2.2.2 to explain a session

**Comment by schnelle** [comment]
Definition require small improvements

- start interacting --> activate
- explicit deactivation to be added

Move to new section in Appendix: Definitions & Terms

**Comment by schnelle** [comment]
Sessions are now described as an optional concept.
