### ISSUE TITLE
client activation strategy

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#7]
from Jim Larson's email [https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0002.html](url)

3.2.2.1 (it should be 3.1.3.1) client activation strategy

Include a client activation strategy involving pointing or clicking to 
select to the desired the target of the activation. This can be done 
with a mouse click or by vision in which the user points to the target.

**Comment by schnelle** [comment]
Add an activation strategy like gesture to talk

**Comment by schnelle** [comment]
Reviewed in meeting
