### ISSUE TITLE
Dialog strategy

### ISSUE THREAD

**Issue by dadahl** [w3c/voiceinteraction#8]
from Jim Larson's email [https://lists.w3.org/Archives/Public/public-voiceinteraction/2021Mar/0002.html](url)

3.2.2.1 dialog strategy

Don’t just list static, preplaned strategies.Add a dialog strategy 
called “dynamic” that determines the next step based on previous steps.

**Comment by dadahl** [comment]
from Jim: maybe we should call this "user-directed" meaning the user chooses the next step
debbie: or "user initiative"
jon: able to handle interrupts, multivariable dialog where the dialog can go in different directions depending on what the user says
jim: user input is unconstrained

**Comment by schnelle** [comment]
Initiative is not part of that list but part of the mentioned strategies. So, the expectation would be that these attributes are described there.

**Comment by schnelle** [comment]
List of strategies is open ended and just examples, so dynamic might be subject to future implementions, not to be added, now.
